# ==== CONFIG ====

## Project Name
PROJECTNAME := Bare_Arduino_Cpp

## Compilers and linkers used
CC := avr-gcc
CXX := avr-g++
OBJCOPY := avr-objcopy
OBJDUMP := avr-objdump
SIZE := avr-size
LD := avr-g++

## INLCUDE OBJECT DUMP AND SIZE??
## avr-size firmware.elf        # flash (text+data) vs RAM (data+bss) usage  ← do this always
## avr-objdump  avr-objdump 


## INCLUDE STUFF NEEDS TO BE ADDED WITH -M FLAGS AND -MDD FLAGS
## That kinda stuff look into it later also about data dumps and memory maps idk also that seems important
## But not neceserally essential

## MCU Specific flags

MCU := atmega328p
MCU_FREQ := 16000000UL
# "-DF_CPU=16000000UL", #IDK
# -Os (?) remove and check if this works for like future whatever if reusing for STM32


## MCU Specific flags 

## Fix Linker Flags I think. Something about standard libraries?
FLAGS    := -mmcu=$(MCU) -DF_CPU=$(MCU_FREQ) -Wall -Wextra -ffunction-sections -fdata-sections -Os $(BUILD_FLAGS) #check if this is good idk
CFLAGS   := $(FLAGS) -std=gnu11
CPPFLAGS := $(FLAGS) -std=gnu++11 -fno-exceptions -fno-rtti

LDFLAGS  := -mmcu=$(MCU)

####################

## C files

SRCS := \
	sources/main.cpp \

VPATH := $(sort $(dir $(SRCS)))

###### OBJECTS FILTERING ############

OBJSC   := $(patsubst %.c,$(BUILD_DIR)/artifacts/%.o, $(filter %.c, $(notdir $(SRCS))))
OBJSCPP := $(patsubst %.cpp,$(BUILD_DIR)/artifacts/%.o, $(filter %.cpp, $(notdir $(SRCS))))

##################

## REVISIT THE THING GENERATED BY CHAT ON THE OTHER THINGY

#$(OBJS): src/%.o : src/%.cpp
 #   $(CXX) $(CPPFLAGS) -c $< $(LIB_PATH) $(LIBS)

##idk

$(BUILD_DIR):
	mkdir -p $@ $@/artifacts	
	@echo "=== Building DEBUG Folder ==="


_build: $(BUILD_DIR)

## Build rules for C and C++ files
$(OBJSCPP): $(BUILD_DIR)/artifacts/%.o: %.cpp
	$(CXX) $(CPPFLAGS) -c $< -o $@

$(OBJSC): $(BUILD_DIR)/artifacts/%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

## Building Rules for ELF

_elf: _objs #$(OBJSC) Eventually add this one
	@echo "=== Building ELF file ==="
	${LD} $(OBJSCPP)  $(LDFLAGS) -o $(BUILD_DIR)/$(PROJECTNAME).elf
	@echo "=== PROGRAM INFO ==="
	${SIZE} $(BUILD_DIR)/$(PROJECTNAME).elf
	@echo "==================="

## Building Rules for HEX

_hex: _elf
	${OBJCOPY} -O ihex -R .eeprom $(BUILD_DIR)/$(PROJECTNAME).elf $(BUILD_DIR)/$(PROJECTNAME).hex
	@echo "=== Building HEX file ==="

## Check the EEPROM stuff seems important


# ===================
_objs: $(OBJSCPP) #$(OBJSC)
	@echo "=== Building OBJ from C files ==="
	@echo "OBJSC:   $(OBJSC)"
	@echo "Using flags: $(CFLAGS)"
	@echo "=== Building OBJ from CPP files ==="
	@echo "OBJSCPP: $(OBJSCPP)"
	@echo "Using flags: $(CPPFLAGS)"

# ===== Targets =====
.PHONY: debug release clean clean_hard

all: debug release
 
debug: TARGET := $(PROJECTNAME)_debug
debug: BUILD_DIR := build/${TARGET}
debug:
	$(MAKE) BUILD_DIR=$(BUILD_DIR) BUILD_FLAGS="-DDEBUG -g" _build
	$(MAKE) BUILD_DIR=$(BUILD_DIR) BUILD_FLAGS="-DDEBUG -g" _hex

#debug: FLAGS += -fno-omit-frame-pointer -fno-inline -g2 -ggdb -O0 
#debug: $(TARGET_OBJS) | $(BUILD_DIR)

release: TARGET := $(PROJECTNAME)_release
release: BUILD_DIR := build/${TARGET}
release:
	$(MAKE) BUILD_DIR=$(BUILD_DIR) BUILD_FLAGS="-DRELEASE" _build
	$(MAKE) BUILD_DIR=$(BUILD_DIR) BUILD_FLAGS="-DRELEASE" _hex

clean:
	-rm -rf build

 ##################333
#debug: TARGET = $(PROJECTNAME)_debug
#debug: TARGET_OBJS  := $(addprefix $(BUILD_DIR)/artifacts/, $(notdir $(patsubst %.c,%.o,$(patsubst %.s,%.o,$(patsubst %.cpp,%.o,$(SRCS))))))
#debug: $(TARGET_OBJS)
#	@echo "=== Building DEBUG version ==="
#	mkdir -p $(BUILD_DIR) ; $(LD) $(TARGET_OBJS) $(LDFLAGS) -o $(BUILD_DIR)/$(TARGET).elf

##stale flag variable issues?


#-include $(OBJSCPP:.o=.d)